[project]
name = "tinychess"
version = "0.0.1"
description = "A minimal chess engine"
authors = [{ name = "dkormann"}]
readme = "readme.md"
license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "torch",
]

[tool.setuptools.packages.find]
where = ["tinychess"]